#!/bin/bash
#PBS -N PNAS_Step4d
#PBS -j oe
#PBS -l nodes=1:ppn=24,walltime=120:00:00
#PBS -V

### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`

ncpu=`cat $PBS_NODEFILE | wc -w`
echo "Number of processors = $ncpu "
### end of information preamble

cd $PBS_O_WORKDIR

echo $PWD

sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 105 300 & 
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 110 300 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 115 300 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 120 300 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 125 300 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 090 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 092 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 095 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 100 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 105 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 110 400 &
sleep 1
bin/eam_mc2 scripts/work/PNAShomo/C4_MEP_calculation.tcl 2000 115 400 &


wait
#wipe $PBS_NODEFILE

