#!/bin/bash
#PBS -N PNAS_Step9d
#PBS -j oe
#PBS -l nodes=1:ppn=24,walltime=120:00:00
#PBS -V

### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`

ncpu=`cat $PBS_NODEFILE | wc -w`
echo "Number of processors = $ncpu "
### end of information preamble

cd $PBS_O_WORKDIR
echo $PWD

sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 100 0.090 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 200 0.090 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 300 0.090 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 400 0.090 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 500 0.090 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 100 0.092 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 200 0.092 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 300 0.092 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 400 0.092 &
sleep 1
bin1/eam_mc2 scripts/work/PNAShomo/C9_get_more_accurate_stress.tcl 500 0.092 &

wait
#wipe $PBS_NODEFILE

