#!/bin/bash
#PBS -N Us-Ni-homo_Step3cc
#PBS -j oe
#PBS -l nodes=1:ppn=24,walltime=120:00:00
#PBS -V

### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`

ncpu=`cat $PBS_NODEFILE | wc -w`
echo "Number of processors = $ncpu "
### end of information preamble

cd $PBS_O_WORKDIR
echo $PWD
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.005 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.015 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.025 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.035 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.045 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.055 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.065 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.075 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.085 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.135 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.145 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 100 0.155 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 200 0.160 &
sleep 1
bin/eam_mc2_mpich scripts/work//Us-Ni-homo//C3_make_non0K_pure_shear_stress_cell.tcl 300 0.175 &

wait
#wipe $PBS_NODEFILE

