#!/bin/sh
# Shell script creating a movie file.
# Orginally downloaded from http://li.mit.edu/Archive/Graphics/A/Compression/vidcompress
# Modified by Keonwook Kang (kwkang@lanl.gov)
# Fri Sep 30 23:53:41 MDT 2011

# see http://www.cscs.ch/~mvalle/mencoder/mencoder.html

# touch ~/.mplayer/mencoder #

##################################################################
# INPUTS
# 
# Source figure file directory
FIG_DIR="./Pngs"

# Figure file format: jpg/png
FIG_FORMAT="png"

# Movie file format: avi/mpg
M_FORMAT="avi"

# Movie file name
M_FILE=Ag-pentatwin-nw-n41-1e8.${M_FORMAT}

# frames per second (Default: 25)
FPS=2

# End of INPUTS
##################################################################



figfile=`ls $FIG_DIR/ | grep --max-count=1 -i .${FIG_FORMAT}`

geometry=`identify -verbose $FIG_DIR/$figfile | grep Geometry | cut -d: -f2`

height=`echo $geometry | cut -dx -f1`
width=`echo $geometry | cut -dx -f2`
width=`echo $width | cut -d+ -f1`

optimal_bitrate=`echo "scale=0; 50 * 25 * $width * $height / 256" | bc -l`

rm -f $M_FILE

opt="vbitrate=$optimal_bitrate:mbd=2:keyint=132:vqblur=1.0:cmp=2:subcmp=2:dia=2:last_pred=3"

mencoder -ovc lavc -lavcopts vcodec=msmpeg4v2:vpass=1:$opt -mf type=${FIG_FORMAT}:fps=${FPS} -nosound -o /dev/null mf://$FIG_DIR/\*.${FIG_FORMAT}
mencoder -ovc lavc -lavcopts vcodec=msmpeg4v2:vpass=2:$opt -mf type=${FIG_FORMAT}:fps=${FPS} -nosound -o $M_FILE mf://$FIG_DIR/\*.${FIG_FORMAT}

#mencoder -ovc lavc -lavcopts vcodec=msmpeg4v2:vpass=1:$opt -mf type=${FIG_FORMAT}:fps=25 -nosound -o /dev/null mf://$FIG_DIR/\*.${FIG_FORMAT}
#mencoder -ovc lavc -lavcopts vcodec=msmpeg4v2:vpass=2:$opt -mf type=${FIG_FORMAT}:fps=25 -nosound -o $M_FILE mf://$FIG_DIR/\*.${FIG_FORMAT}

