#!/bin/bash
#PBS -N PNAS_Step1-1000a
#PBS -j oe
#PBS -l nodes=1:ppn=24,walltime=999:00:00
#PBS -V

### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo The working directory is `echo $PBS_O_WORKDIR`
echo This job runs on the following nodes:
echo `cat $PBS_NODEFILE`

ncpu=`cat $PBS_NODEFILE | wc -w`
echo "Number of processors = $ncpu "
### end of information preamble

# cd $PBS_O_WORKDIR
cd /home/xzhang11/Planet/Libs/MD++.svn
echo $PWD

sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.0200 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.0400  &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.0800 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.1000 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.1200 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.1400 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.1600  &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.1800 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.2000 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.2200 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.2400 &
sleep 1
bin1/sworigsige_mc2 scripts/work/SiGeHomo-sworig/ss_sige.tcl 1 1000 0.2600 &

sleep 1

wait
#wipe $PBS_NODEFILE

